### ISSUE TITLE
problem with wanb: api_key not configured 

### ISSUE THREAD

**Issue by dung2603** [isl-org/ZoeDepth#112]
wandb: ERROR api_key not configured (no-tty). call wandb.login(key=[your_api_key])
Traceback (most recent call last):
  File "/content/ZoeDepth/train_mono.py", line 169, in <module>
    mp.spawn(main_worker, nprocs=ngpus_per_node,
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/content/ZoeDepth/train_mono.py", line 104, in main_worker
    trainer.train()
  File "/content/ZoeDepth/zoedepth/trainers/base_trainer.py", line 155, in train
    wandb.init(project=self.config.project, name=self.config.experiment_id, config=flatten(self.config), dir=self.config.root,
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 1105, in init
    wi.setup(kwargs)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 276, in setup
    wandb_login._login(
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_login.py", line 298, in _login
    wlogin.prompt_api_key()
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_login.py", line 228, in prompt_api_key
    raise UsageError("api_key not configured (no-tty). call " + directive)
wandb.errors.UsageError: api_key not configured (no-tty). call wandb.login(key=[your_api_key])

**Comment by YacineDeghaies** [comment]
Did you fix this ?

**Comment by dung2603** [comment]
> Did you fix this ?

I fixed it

**Comment by YacineDeghaies** [comment]
> I fixed it

How ?

**Comment by dung2603** [comment]
> > I fixed it
> 
> How ?

Access wandb.ai then read introduction
