### ISSUE TITLE
HuggingFace space is not working

### ISSUE THREAD

**Issue by bch77** [isl-org/ZoeDepth#40]
Runtime error
Traceback (most recent call last):
  File "app.py", line 22, in <module>
    model = torch.hub.load('isl-org/ZoeDepth', "ZoeD_N", pretrained=True).to(DEVICE).eval()
  File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages/torch/hub.py", line 397, in load
    repo_or_dir = _get_cache_or_reload(repo_or_dir, force_reload, verbose, skip_validation)
  File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages/torch/hub.py", line 185, in _get_cache_or_reload
    _validate_not_a_forked_repo(repo_owner, repo_name, branch)
  File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages/torch/hub.py", line 147, in _validate_not_a_forked_repo
    response = json.loads(_read_url(Request(url, headers=headers)))
  File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages/torch/hub.py", line 130, in _read_url
    with urlopen(url) as r:
  File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: rate limit exceeded
Container logs:

Traceback (most recent call last):
  File "app.py", line 22, in <module>
    model = torch.hub.load('isl-org/ZoeDepth', "ZoeD_N", pretrained=True).to(DEVICE).eval()
  File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages/torch/hub.py", line 397, in load
    repo_or_dir = _get_cache_or_reload(repo_or_dir, force_reload, verbose, skip_validation)
  File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages/torch/hub.py", line 185, in _get_cache_or_reload
    _validate_not_a_forked_repo(repo_owner, repo_name, branch)
  File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages/torch/hub.py", line 147, in _validate_not_a_forked_repo
    response = json.loads(_read_url(Request(url, headers=headers)))
  File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages/torch/hub.py", line 130, in _read_url
    with urlopen(url) as r:
  File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: rate limit exceeded

**Comment by shariqfarooq123** [comment]
Thanks for reporting! The demo is up again for now. 

The error itself is quite strange. Rate limit errors should only appear if many "API" calls are made in a given amount of time. Also, this line (#line22 in app.py) should only reach the first time the app is started. This would mean either: 
- More than 5000 restarts were triggered for the HuggingFace space (Unlikely)
- One or few restarts were triggered and `torch.hub.load` calls the GitHub API many times (>1000 PER HOUR!), indicating a bug in [pytorch/pytorch](https://github.com/pytorch/pytorch)
