### ISSUE TITLE
Sanity checked not passed

### ISSUE THREAD

**Issue by albertotono** [isl-org/ZoeDepth#74]
I am getting this message after running the sanity.py checks. 

I have latest CUDA (12.1) and PyTorch 1.13.1

Here for the hub

```
 File "/home/ubuntu/ZoeDepth/sanity_hub.py", line 41, in <module>
    model = torch.hub.load(".", "ZoeD_K", source="local", pretrained=True)
  File "/opt/conda/lib/python3.10/site-packages/torch/hub.py", line 542, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/hub.py", line 572, in _load_local
    model = entry(*args, **kwargs)
  File "/home/ubuntu/ZoeDepth/./hubconf.py", line 110, in ZoeD_K
    model = build_model(config)
  File "/home/ubuntu/ZoeDepth/zoedepth/models/builder.py", line 51, in build_model
    return get_version(config.version_name).build_from_config(config)
  File "/home/ubuntu/ZoeDepth/zoedepth/models/zoedepth/zoedepth_v1.py", line 250, in build_from_config
    return ZoeDepth.build(**config)
  File "/home/ubuntu/ZoeDepth/zoedepth/models/zoedepth/zoedepth_v1.py", line 245, in build
    model = load_state_from_resource(model, pretrained_resource)
  File "/home/ubuntu/ZoeDepth/zoedepth/models/model_io.py", line 84, in load_state_from_resource
    return load_state_dict_from_url(model, url, progress=True)
  File "/home/ubuntu/ZoeDepth/zoedepth/models/model_io.py", line 61, in load_state_dict_from_url
    return load_state_dict(model, state_dict)
  File "/home/ubuntu/ZoeDepth/zoedepth/models/model_io.py", line 49, in load_state_dict
    model.load_state_dict(state)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ZoeDepth:
        Unexpected key(s) in state_dict: "core.core.pretrained.model.blocks.0.attn.relative_position_index", "core.core.pretrained.model.blocks.1.attn.relative_position_index", "core.core.pretrained.model.blocks.2.attn.relative_position_index", "core.core.pretrained.model.blocks.3.attn.relative_position_index", "core.core.pretrained.model.blocks.4.attn.relative_position_index", "core.core.pretrained.model.blocks.5.attn.relative_position_index", "core.core.pretrained.model.blocks.6.attn.relative_position_index", "core.core.pretrained.model.blocks.7.attn.relative_position_index", "core.core.pretrained.model.blocks.8.attn.relative_position_index", "core.core.pretrained.model.blocks.9.attn.relative_position_index", "core.core.pretrained.model.blocks.10.attn.relative_position_index", "core.core.pretrained.model.blocks.11.attn.relative_position_index", "core.core.pretrained.model.blocks.12.attn.relative_position_index", "core.core.pretrained.model.blocks.13.attn.relative_position_index", "core.core.pretrained.model.blocks.14.attn.relative_position_index", "core.core.pretrained.model.blocks.15.attn.relative_position_index", "core.core.pretrained.model.blocks.16.attn.relative_position_index", "core.core.pretrained.model.blocks.17.attn.relative_position_index", "core.core.pretrained.model.blocks.18.attn.relative_position_index", "core.core.pretrained.model.blocks.19.attn.relative_position_index", "core.core.pretrained.model.blocks.20.attn.relative_position_index", "core.core.pretrained.model.blocks.21.attn.relative_position_index", "core.core.pretrained.model.blocks.22.attn.relative_position_index", "core.core.pretrained.model.blocks.23.attn.relative_position_index". 
```

here for the sanity.py

```
Traceback (most recent call last):
  File "/home/ubuntu/ZoeDepth/sanity.py", line 49, in <module>
    model = build_model(conf).to(DEVICE)
  File "/home/ubuntu/ZoeDepth/zoedepth/models/builder.py", line 51, in build_model
    return get_version(config.version_name).build_from_config(config)
  File "/home/ubuntu/ZoeDepth/zoedepth/models/zoedepth/zoedepth_v1.py", line 250, in build_from_config
    return ZoeDepth.build(**config)
  File "/home/ubuntu/ZoeDepth/zoedepth/models/zoedepth/zoedepth_v1.py", line 245, in build
    model = load_state_from_resource(model, pretrained_resource)
  File "/home/ubuntu/ZoeDepth/zoedepth/models/model_io.py", line 84, in load_state_from_resource
    return load_state_dict_from_url(model, url, progress=True)
  File "/home/ubuntu/ZoeDepth/zoedepth/models/model_io.py", line 61, in load_state_dict_from_url
    return load_state_dict(model, state_dict)
  File "/home/ubuntu/ZoeDepth/zoedepth/models/model_io.py", line 49, in load_state_dict
    model.load_state_dict(state)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ZoeDepth:
        Unexpected key(s) in state_dict: "core.core.pretrained.model.blocks.0.attn.relative_position_index", "core.core.pretrained.model.blocks.1.attn.relative_position_index", "core.core.pretrained.model.blocks.2.attn.relative_position_index", "core.core.pretrained.model.blocks.3.attn.relative_position_index", "core.core.pretrained.model.blocks.4.attn.relative_position_index", "core.core.pretrained.model.blocks.5.attn.relative_position_index", "core.core.pretrained.model.blocks.6.attn.relative_position_index", "core.core.pretrained.model.blocks.7.attn.relative_position_index", "core.core.pretrained.model.blocks.8.attn.relative_position_index", "core.core.pretrained.model.blocks.9.attn.relative_position_index", "core.core.pretrained.model.blocks.10.attn.relative_position_index", "core.core.pretrained.model.blocks.11.attn.relative_position_index", "core.core.pretrained.model.blocks.12.attn.relative_position_index", "core.core.pretrained.model.blocks.13.attn.relative_position_index", "core.core.pretrained.model.blocks.14.attn.relative_position_index", "core.core.pretrained.model.blocks.15.attn.relative_position_index", "core.core.pretrained.model.blocks.16.attn.relative_position_index", "core.core.pretrained.model.blocks.17.attn.relative_position_index", "core.core.pretrained.model.blocks.18.attn.relative_position_index", "core.core.pretrained.model.blocks.19.attn.relative_position_index", "core.core.pretrained.model.blocks.20.attn.relative_position_index", "core.core.pretrained.model.blocks.21.attn.relative_position_index", "core.core.pretrained.model.blocks.22.attn.relative_position_index", "core.core.pretrained.model.blocks.23.attn.relative_position_index". 
```

**Comment by albertotono** [comment]
https://github.com/isl-org/ZoeDepth/issues/72 this solved it.
